# Generated by Django 4.2 on 2023-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_dam_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dam',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='dam',
            name='user_name',
        ),
        migrations.AddField(
            model_name='dam',
            name='canvas',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
